package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;

    public String addStudent(Student student) {
        //id is autogenerated, other attribute as given as input with help of postman

        //Card should create automatically while student is added
        Card card=new Card(); //id,creation time and updated time is autogenerated
        card.setCardStatus(CardStatus.ACTIVATED); //setting the status of the card
        card.setStudentVariableName(student); //set the foreign key attribute to the entity

        //set the card attribute of student//all the other attributes are wrapped in student object
        student.setCard(card);

        //As this is bidirectional mapping we dont need to save both card and student.
        //if we save student ,the card will be automatically saved to db
        studentRepository.save(student);

        return "Student added and Card for the Student Created";
    }
}
