package com.example.Student_Library_Management_System.Models;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@Entity
@Table(name = "card_info")
public class Card {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //autogenerated id used as primary key
    private int id;

    @CreationTimestamp //Auto time stamp creation time//Use util date not sql date
    private Date createOn;

    @UpdateTimestamp //set the time when the entity is updated
    private Date updatedOn;

    @Enumerated(value = EnumType.STRING) //storing the enum in form of string in sql table//as enum is not there in sql
    private CardStatus cardStatus;
    //its necessary to have getter and setter of cardstatus variable



    //Student & Card mapping
            //(here Card is child w.r.t Student)
    @OneToOne
    //@JoinColumn(name = "age") //if you want to set the age as foreign key
    @JoinColumn //join by adding a foreign key to column//here by default foreign key is : primary key of Student
    private Student studentVariableName; //this variable will be used in Student class while doing bidirectional mapping
    //it's necessary to have getter and setter of studentVariableName variable


    //Card & Book mapping
            //here Card is parent w.r.t Book
    @OneToMany(mappedBy = "card",cascade = CascadeType.ALL)
    private List<Book> booksIssued;



    //constructor
    public Card() {
        booksIssued=new ArrayList<>();
    }

    //getter and setter

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Date getCreateOn() {
        return createOn;
    }

    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    public Date getUpdatedOn() {
        return updatedOn;
    }

    public void setUpdatedOn(Date updatedOn) {
        this.updatedOn = updatedOn;
    }

    public CardStatus getCardStatus() {
        return cardStatus;
    }

    public void setCardStatus(CardStatus cardStatus) {
        this.cardStatus = cardStatus;
    }

    public Student getStudentVariableName() {
        return studentVariableName;
    }

    public void setStudentVariableName(Student studentVariableName) {
        this.studentVariableName = studentVariableName;
    }

    public List<Book> getBooksIssued() {
        return booksIssued;
    }

    public void setBooksIssued(List<Book> booksIssued) {
        this.booksIssued = booksIssued;
    }
}
